apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook-prod

namePrefix: prod-

commonLabels:
  environment: prod
  app: guestbook

bases:
  - ../../base

images:
  - name: gcr.io/google-samples/gb-frontend:v5
    newTag: "0.2"

replicas:
  - name: guestbook-ui
    count: 3

configMapGenerator:
  - name: guestbook-config
    literals:
      - ENVIRONMENT=production