apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook-dev

namePrefix: dev-

commonLabels:
  environment: dev
  app: guestbook

bases:
  - ../../base

images:
  - name: gcr.io/google-samples/gb-frontend:v5
    newTag: "0.1"

replicas:
  - name: guestbook-ui
    count: 1

configMapGenerator:
  - name: guestbook-config
    literals:
      - ENVIRONMENT=development